### PR TITLE
3-D structure protein viewer functionality in demo

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a concept for a protein viewer for our demo here

It is tempting to put the protein viewer right in the react-msaview package to make it tightly integrated but instead, I think I am going to put it in the app directory e.g. the create-react-app demo is in app and the library for MSA vieweing is the react-msaview package in the lib directory

I wanted to try to be bleeding edge so it is trying out NGL http://nglviewer.org/ngl/gallery/index.html

Some features I liked about NGL is that it can display multiple structures at once. This way, you could put the protein from mouse and human laid over each other and see the differences. I can also use the ranges provided so that you are only viewing the range of sequence specified in the alignment.

Wiring up hover actions and such are ongoing

### CODE REVIEW

**Comment by cmdcolin** [comment]
This is basically getting there conceptually....mouseover the MSA doesn't highlight the node on the protein but the protein has a way to highlight the location on the MSA (still needs validation)

I may merge just to get the demo out there

**Comment by ihh** [comment]
This all looks v cool

In the longer term I wonder if we should make the PDB viewer? A modularly configurable component/plugin. Adopting websites will often have their own preferred 3D structure viewer (e.g. this was the case with Interpro when I demo'd ABrowse for them, although to be fair NGL *was* the viewer they were using)

**Comment by cmdcolin** [comment]
Indeed, that was my design goal so that should be good as implemented here

The protein viewer is independent from the react-msaview library (which just displays the MSA and the tree) and the react-msaview just has the idea of "adding things to a selection". The app containing the MSA view can interpret the selection however it wants, and in this case, the app has NGL display the proteins

**Comment by cmdcolin** [comment]
Here is how the demo looks with this branch, went ahead and deployed to the website. It remembers the state via the URL so here it is with NGL loaded on the covid stockholm file https://gmod.github.io/react-msaview/?data=%7B%22id%22%3A%22YUkH81xbT%22%2C%22type%22%3A%22MsaView%22%2C%22height%22%3A550%2C%22treeAreaWidth%22%3A400%2C%22treeWidth%22%3A300%2C%22rowHeight%22%3A20%2C%22scrollY%22%3A0%2C%22scrollX%22%3A0%2C%22blockSize%22%3A1000%2C%22selected%22%3A%5B%7B%22id%22%3A%22POLG_RHDVF%2F1288-1730%22%2C%22pdb%22%3A%221khw%22%7D%5D%2C%22labelsAlignRight%22%3Afalse%2C%22colWidth%22%3A16%2C%22showBranchLen%22%3Atrue%2C%22bgColor%22%3Atrue%2C%22drawTree%22%3Atrue%2C%22drawNodeBubbles%22%3Atrue%2C%22colorSchemeName%22%3A%22maeditor%22%2C%22msaFilehandle%22%3A%7B%22uri%22%3A%22https%3A%2F%2Fihh.github.io%2Fabrowse%2Fbuild%2Fpfam-cov2.stock%22%7D%2C%22currentAlignment%22%3A0%2C%22collapsed%22%3A%5B%5D%7D#

**Pull request merged**
